---

- hosts: all
  become: true
  tasks:
    - name: update the cache of ubuntu machine
      apt:
        update_cache: true
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache2 at the ubuntu machine
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Support for Apache2, PHP for ubuntu machine
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: update the cache of centos machine
      yum:
        update_cache: yes
        state: latest
      when: ansible_distribution == "CentOS"

    - name: Install Apache2 for centos machine
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "CentOS"

    - name: Support for Apache2 PHP for centos machine
      yum:
        name: php
        state: latest
      when: ansible_distribution == "CentOS"
