---

- hosts: all
  become: true
  tasks:

    - name: Update Cache for centos Machine
      tags: always
      yum:
        update_cache: true 
      changed_when: false    
      when: ansible_distribution == "CentOS"
    
    
    - name: Update Cache for Ubuntu Machine
      tags: always
      apt:
        update_cache: true
      changed_when: false    
      when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

    - name: add ssh key for alia
      tags: always
      authorized_key:
        user: alia
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGRqZxtvvzGOGMXBCXA/AcESFDKnfzF9aJJXQSiEaIw1 ansible to access remote machines"


